name: myapp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0-282.3.beta <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_riverpod: ^2.5.1
  go_router: ^14.1.2
  rive: ^0.13.4
  dio: ^5.4.3+1
  intl: ^0.19.0
  freezed: ^2.5.2
  auto_size_text: ^3.0.0
  animated_text_kit: ^4.2.2
  infinite_scroll_pagination: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/image/
    - assets/animations/
